version: 2
jobs:
  build:
    working_directory: ~/ssrPwaTest
    docker:
    - image: circleci/node:8-browsers
    steps:
    - checkout
    - restore_cache:
        key: ssrPwaTest-{{ .Branch }}-{{ checksum "package-lock.json" }}
    - run: npm install
    - save_cache:
        key: ssrPwaTest-{{ .Branch }}-{{ checksum "package-lock.json" }}
        paths:
        - "node_modules"
    - run: npm run test -- --single-run --no-progress --browser=ChromeHeadlessCI
    - run: npm run e2e -- --no-progress --config=protractor-ci.conf.js
